image: fjolsvin/gitpod-python:latest

tasks:
  - init: >
      chmod +x contrib/scripts/* &&
      make  init &&
      make -j$(nproc) run
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
ports:
  - port: 6080
    onOpen: open-preview
vscode:
  extensions:
    - wmaurer.change-case
    - emeraldwalk.RunOnSave
    - vscode-snippet.snippet
    - bungcip.better-toml
    - streetsidesoftware.code-spell-checker
    - zalo.symplex
    - yixian.yapep
    - mechatroner.rainbow-csv
    - phplasma.csv-to-table
    - wayou.vscode-todo-highlight
    - redhat.vscode-yaml
    - ms-python.python
    - EditorConfig.EditorConfig
