image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      poetry install &&
      [ -r .venv/pyvenv.cfg ] &&
      sed -i "/include-system-site-packages/d" .venv/pyvenv.cfg &&
      echo "include-system-site-packages = true" | tee -a .venv/pyvenv.cfg

  - command: >
      [ -r .venv/pyvenv.cfg ] &&
      sed -i "/include-system-site-packages/d" .venv/pyvenv.cfg &&
      echo "include-system-site-packages = true" | tee -a .venv/pyvenv.cfg

ports:
  - port: 3000-10000
    onOpen: ignore
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true

vscode:
  extensions:
    - ms-python.python
    - karyfoundation.comment
    - bungcip.better-toml
    - mutantdino.resourcemonitor
    - redhat.vscode-yaml
    - streetsidesoftware.code-spell-checker
    - vscode-snippet.snippet
    - wayou.vscode-todo-highlight
    - wmaurer.change-case
    - yzane.markdown-pdf
    - yzhang.markdown-all-in-one
    - aaron-bond.better-comments
    - bungcip.better-toml
    - EditorConfig.EditorConfig
    - emeraldwalk.RunOnSave
    - kevinkyang.auto-comment-blocks
    - ms-azuretools.vscode-docker
    - wholroyd.hcl
    - skellock.just
    - tomoyukim.vscode-mermaid-editor
    - gruntfuggly.todo-tree
