FROM gitpod/workspace-full-vnc:branch-jx-python-tk
# FROM gitpod/workspace-full-vnc:latest
# USER root
# ARG SHELLCHECK_VERSION=stable
# ARG SHELLCHECK_FORMAT=gcc
# ENV DEBIAN_FRONTEND=noninteractive
# RUN apt-get update && apt-get install -yq curl wget aria2 
# RUN curl -fsSL \
#     https://raw.githubusercontent.com/da-moon/core-utils/master/bin/fast-apt | sudo bash -s -- \
#     --init || true;
# RUN aria2c "https://storage.googleapis.com/shellcheck/shellcheck-${SHELLCHECK_VERSION}.linux.x86_64.tar.xz"
# RUN tar -xvf shellcheck-"${SHELLCHECK_VERSION}".linux.x86_64.tar.xz
# RUN cp shellcheck-"${SHELLCHECK_VERSION}"/shellcheck /usr/bin/
# RUN shellcheck --version
# RUN echo 'export PATH="/workspace/project_template/contrib/scripts:$PATH"' >>~/.bashrc
# RUN curl -fsSL \
#     https://raw.githubusercontent.com/da-moon/core-utils/master/bin/get-hashi | sudo bash -s -- || true;
# RUN wget -q -O /usr/bin/run-sc https://raw.githubusercontent.com/da-moon/core-utils/master/bin/run-sc
# RUN chmod +x "/usr/bin/run-sc"
# RUN wget -q -O /usr/bin/gitt https://raw.githubusercontent.com/da-moon/core-utils/master/bin/gitt
# RUN chmod +x "/usr/bin/gitt"
# RUN gitt --init || true;
# RUN apt-get update && apt-get install -yq tk-dev python-tk python3-tk

# CMD ["bash"] 
